apiVersion: v1
kind: Service
metadata:
  name: zomato
  namespace: default
  labels:
    app: zomato
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: zomato
